[project]
name = "finance-tracker"
version = "0.1.0"
description = "An app to track your monthly transactions against a budget."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlmodel>=0.0.24",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
