"""Drop trans_date date type

Revision ID: 0ccc51a717d9
Revises: cebeb286cc8e
Create Date: 2025-07-18 13:10:11.565533

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ccc51a717d9"
down_revision: Union[str, Sequence[str], None] = "cebeb286cc8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "trans_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("trans_date", sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
