"""Add trans_date date type

Revision ID: 39ea7adff076
Revises: 0ccc51a717d9
Create Date: 2025-07-18 13:10:40.145199

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39ea7adff076"
down_revision: Union[str, Sequence[str], None] = "0ccc51a717d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("trans_date", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "trans_date")
    # ### end Alembic commands ###
